scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']
  - job_name: 'jupyterhub'
    scrape_interval: 5s
    static_configs:
    - targets: ['jupyterhub:8080']  
    authorization:
      credentials: "ec01e80edf4f4846b43787c486cb3159"
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: 'dcgm_exporter'
    static_configs:
      - targets: ['dcgm_exporter:9400']
  
rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
