apiVersion: v1
kind: PersistentVolume
metadata:
  name: katib-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs_share
    server: 10.1.1.9
  persistentVolumeReclaimPolicy: Retain
